/**
 * Sales drawer chrome — reuse appointment drawer layout values (already tuned to Figma).
 * Purpose spine uses shared DRAWER_SPINE_* (rounded top-left + bottom-left).
 */
export {
  APPOINTMENT_DRAWER_SHELL_CLASS as SALES_DRAWER_SHELL_CLASS,
  APPOINTMENT_DRAWER_SHELL_HEADER_CLASS as SALES_DRAWER_SHELL_HEADER_CLASS,
  APPOINTMENT_DRAWER_BODY_INSET_CLASS as SALES_DRAWER_BODY_INSET_CLASS,
  APPOINTMENT_DRAWER_FOOTER_CLASS as SALES_DRAWER_FOOTER_CLASS,
  APPOINTMENT_DRAWER_FOOTER_INNER_CLASS as SALES_DRAWER_FOOTER_INNER_CLASS,
  APPOINTMENT_DRAWER_PRIMARY_BUTTON_CLASS as SALES_DRAWER_PRIMARY_BUTTON_CLASS,
  APPOINTMENT_DRAWER_HEADER_ACTION_CLASS as SALES_DRAWER_HEADER_ACTION_CLASS,
  APPOINTMENT_DRAWER_FIELD_CLASS as SALES_DRAWER_FIELD_CLASS,
  APPOINTMENT_DRAWER_SELECT_TRIGGER_CLASS as SALES_DRAWER_SELECT_TRIGGER_CLASS,
  APPOINTMENT_DRAWER_FORM_FIELDS_CLASS as SALES_DRAWER_FORM_FIELDS_CLASS,
  APPOINTMENT_DRAWER_CLIENT_CARD_CLASS as SALES_DRAWER_CLIENT_CARD_CLASS,
  APPOINTMENT_DRAWER_CLIENT_AVATAR_CLASS as SALES_DRAWER_CLIENT_AVATAR_CLASS,
  APPOINTMENT_DRAWER_CLIENT_AVATAR_FALLBACK_CLASS as SALES_DRAWER_CLIENT_AVATAR_FALLBACK_CLASS,
  APPOINTMENT_DRAWER_CLIENT_NAME_CLASS as SALES_DRAWER_CLIENT_NAME_CLASS,
  APPOINTMENT_DRAWER_CLIENT_SINCE_CLASS as SALES_DRAWER_CLIENT_SINCE_CLASS,
  APPOINTMENT_DRAWER_SERVICE_CARD_CLASS as SALES_DRAWER_SERVICE_CARD_CLASS,
  APPOINTMENT_DRAWER_SERVICE_TITLE_CLASS as SALES_DRAWER_SERVICE_TITLE_CLASS,
  APPOINTMENT_DRAWER_SERVICE_PRICE_CLASS as SALES_DRAWER_SERVICE_PRICE_CLASS,
  APPOINTMENT_DRAWER_SERVICE_PROVIDER_CLASS as SALES_DRAWER_SERVICE_PROVIDER_CLASS,
} from "@/features/appointments/styles/appointment-drawer-tokens";

export {
  DRAWER_SPINE_CLASS as SALES_DRAWER_SPINE_CLASS,
  DRAWER_SPINE_LABEL_CLASS as SALES_DRAWER_SPINE_LABEL_CLASS,
} from "@/lib/design/drawer-shell-tokens";

/** Vertical purpose labels for sales drawers (Figma). */
export const SALES_DRAWER_SPINE_LABELS = {
  sale: "SALE",
  options: "OPTIONS",
  checkout: "CHECKOUT",
  payment: "PAYMENT",
} as const;
