import type { ConditionDefinition } from '../types/automation-registry.types';

function cond(
  key: string,
  category: ConditionDefinition['category'],
  label: string,
  description: string,
  valueType: ConditionDefinition['valueType'],
  implementationStatus: ConditionDefinition['implementationStatus'],
  enumValues?: string[],
): ConditionDefinition {
  return {
    key,
    category,
    label,
    description,
    valueType,
    implementationStatus,
    enumValues,
  };
}

export const CONDITION_REGISTRY: ConditionDefinition[] = [
  cond(
    'contact.has_tag',
    'contact',
    'Has tag',
    'Contact has a specific tag.',
    'tag',
    'planned',
  ),
  cond(
    'contact.has_email',
    'contact',
    'Has email',
    'Contact has an email address on file.',
    'boolean',
    'implemented',
  ),
  cond(
    'contact.has_phone',
    'contact',
    'Has phone',
    'Contact has a phone number on file.',
    'boolean',
    'implemented',
  ),
  cond(
    'contact.field_equals',
    'contact',
    'Field equals',
    'Contact profile field equals a value.',
    'string',
    'planned',
  ),
  cond(
    'lead.stage_is',
    'lead',
    'Stage is',
    'Lead is in a specific pipeline stage.',
    'uuid',
    'planned',
  ),
  cond(
    'lead.pipeline_is',
    'lead',
    'Pipeline is',
    'Lead belongs to a specific pipeline.',
    'uuid',
    'planned',
  ),
  cond(
    'lead.assigned_to',
    'lead',
    'Assigned to',
    'Lead is assigned to a team member.',
    'uuid',
    'planned',
  ),
  cond(
    'appointment.service_is',
    'appointment',
    'Service is',
    'Appointment uses a specific service.',
    'uuid',
    'planned',
  ),
  cond(
    'appointment.calendar_is',
    'appointment',
    'Calendar is',
    'Appointment is on a specific calendar.',
    'uuid',
    'implemented',
  ),
  cond(
    'appointment.status_is',
    'appointment',
    'Status is',
    'Appointment has a specific status.',
    'enum',
    'implemented',
    ['scheduled', 'confirmed', 'completed', 'cancelled', 'no_show'],
  ),
  cond(
    'appointment.staff_is',
    'appointment',
    'Staff is',
    'Appointment is assigned to a staff member.',
    'uuid',
    'planned',
  ),
  cond(
    'form.field_equals',
    'form',
    'Field equals',
    'Form submission field equals a value.',
    'string',
    'planned',
  ),
  cond(
    'form.field_contains',
    'form',
    'Field contains',
    'Form submission field contains text.',
    'string',
    'planned',
  ),
  cond(
    'finance.amount_greater_than',
    'finance',
    'Amount greater than',
    'Invoice or estimate total exceeds a threshold.',
    'number',
    'planned',
  ),
  cond(
    'finance.status_is',
    'finance',
    'Status is',
    'Invoice or estimate has a specific status.',
    'enum',
    'implemented',
    ['draft', 'sent', 'paid', 'overdue', 'cancelled', 'accepted', 'declined'],
  ),
  cond(
    'contact_history.has_future_appointment',
    'contact_history',
    'Has future appointment',
    'Contact has an upcoming scheduled appointment.',
    'boolean',
    'planned',
  ),
  cond(
    'contact_history.has_past_appointment',
    'contact_history',
    'Has past appointment',
    'Contact has a completed past appointment.',
    'boolean',
    'planned',
  ),
];

export const CONDITION_BY_KEY = Object.fromEntries(
  CONDITION_REGISTRY.map((c) => [c.key, c]),
) as Record<string, ConditionDefinition>;
