import type { CustomValueDefinition } from '../types/automation-registry.types';
import { applyPlatformAudiencesToCustomValues } from '../utils/automation-audience.util';

function cv(
  category: CustomValueDefinition['category'],
  field: string,
  label: string,
  description: string,
  resolver: string,
  implementationStatus: CustomValueDefinition['implementationStatus'],
  example?: string,
): CustomValueDefinition {
  return {
    key: `${category}.${field}`,
    category,
    label,
    description,
    resolver,
    implementationStatus,
    example,
  };
}

export const CUSTOM_VALUE_REGISTRY: CustomValueDefinition[] = [
  // Contact (10)
  cv(
    'contact',
    'first_name',
    'First name',
    'Contact first name.',
    'contact.firstName',
    'implemented',
    'Jane',
  ),
  cv(
    'contact',
    'last_name',
    'Last name',
    'Contact last name.',
    'contact.lastName',
    'implemented',
    'Doe',
  ),
  cv(
    'contact',
    'full_name',
    'Full name',
    'Contact display name.',
    'contact.fullName',
    'implemented',
    'Jane Doe',
  ),
  cv(
    'contact',
    'name',
    'Name',
    'Alias for contact display name.',
    'contact.fullName',
    'implemented',
    'Jane Doe',
  ),
  cv(
    'contact',
    'email',
    'Email',
    'Primary email address.',
    'contact.email',
    'implemented',
    'jane@example.com',
  ),
  cv(
    'contact',
    'phone',
    'Phone',
    'Primary phone number.',
    'contact.phone',
    'implemented',
    '+1 555 0100',
  ),
  cv(
    'contact',
    'company_name',
    'Company name',
    'Company associated with the contact.',
    'contact.companyName',
    'implemented',
    'Acme Inc',
  ),
  cv(
    'contact',
    'source',
    'Source',
    'How the contact was acquired.',
    'contact.source',
    'implemented',
    'Website',
  ),
  cv(
    'contact',
    'tags',
    'Tags',
    'Comma-separated contact tags.',
    'contact.tags',
    'planned',
  ),
  cv(
    'contact',
    'birthdate',
    'Birthdate',
    'Contact date of birth.',
    'contact.birthdate',
    'stub',
    '1990-05-15',
  ),

  // Business (8)
  cv(
    'business',
    'name',
    'Business name',
    'Tenant business name.',
    'business.name',
    'implemented',
    'Sunrise MedSpa',
  ),
  cv(
    'business',
    'email',
    'Business email',
    'Default business email.',
    'business.email',
    'implemented',
    'hello@sunrise.com',
  ),
  cv(
    'business',
    'phone',
    'Business phone',
    'Business phone number.',
    'business.phone',
    'implemented',
    '+1 555 0200',
  ),
  cv(
    'business',
    'address',
    'Business address',
    'Formatted business address.',
    'business.address',
    'implemented',
    '123 Main St',
  ),
  cv(
    'business',
    'timezone',
    'Timezone',
    'Business timezone.',
    'business.timezone',
    'implemented',
    'America/New_York',
  ),
  cv(
    'business',
    'currency',
    'Currency',
    'Default currency code.',
    'business.currency',
    'implemented',
    'USD',
  ),
  cv(
    'business',
    'website',
    'Website',
    'Business website URL.',
    'business.website',
    'planned',
  ),
  cv(
    'business',
    'logo_url',
    'Logo URL',
    'Business logo image URL.',
    'business.logoUrl',
    'planned',
  ),

  // User (5)
  cv(
    'user',
    'name',
    'User name',
    'Team member display name.',
    'user.name',
    'implemented',
    'Alex Smith',
  ),
  cv(
    'user',
    'first_name',
    'First name',
    'Team member first name.',
    'user.firstName',
    'planned',
  ),
  cv(
    'user',
    'last_name',
    'Last name',
    'Team member last name.',
    'user.lastName',
    'planned',
  ),
  cv(
    'user',
    'email',
    'User email',
    'Team member email.',
    'user.email',
    'implemented',
    'alex@sunrise.com',
  ),
  cv(
    'user',
    'role',
    'Role',
    'Team member role.',
    'user.role',
    'implemented',
    'Admin',
  ),

  // Appointment (12)
  cv(
    'appointment',
    'title',
    'Title',
    'Appointment title.',
    'appointment.title',
    'implemented',
    'Consultation',
  ),
  cv(
    'appointment',
    'start_at',
    'Start time',
    'Appointment start date/time.',
    'appointment.startAt',
    'implemented',
    'Jun 20, 2026 10:00 AM',
  ),
  cv(
    'appointment',
    'end_at',
    'End time',
    'Appointment end date/time.',
    'appointment.endAt',
    'implemented',
    'Jun 20, 2026 11:00 AM',
  ),
  cv(
    'appointment',
    'previous_start_at',
    'Previous start time',
    'Prior start time after reschedule.',
    'appointment.previousStartAt',
    'planned',
  ),
  cv(
    'appointment',
    'status',
    'Status',
    'Appointment status.',
    'appointment.status',
    'implemented',
    'confirmed',
  ),
  cv(
    'appointment',
    'calendar_name',
    'Calendar name',
    'Calendar the appointment is on.',
    'appointment.calendarName',
    'implemented',
    'Dr. Smith',
  ),
  cv(
    'appointment',
    'service_name',
    'Service name',
    'Booked service name.',
    'appointment.serviceName',
    'implemented',
    'Facial',
  ),
  cv(
    'appointment',
    'staff_name',
    'Staff name',
    'Assigned staff member.',
    'appointment.staffName',
    'planned',
  ),
  cv(
    'appointment',
    'location',
    'Location',
    'Appointment location.',
    'appointment.location',
    'planned',
  ),
  cv(
    'appointment',
    'public_booking_url',
    'Booking URL',
    'Public reschedule or booking link.',
    'appointment.publicBookingUrl',
    'planned',
  ),
  cv(
    'appointment',
    'notes',
    'Notes',
    'Internal appointment notes.',
    'appointment.notes',
    'planned',
  ),
  cv(
    'appointment',
    'duration_minutes',
    'Duration',
    'Appointment length in minutes.',
    'appointment.durationMinutes',
    'implemented',
    '60',
  ),

  // Calendar (3)
  cv(
    'calendar',
    'name',
    'Name',
    'Calendar display name.',
    'calendar.name',
    'implemented',
    'Dr. Smith',
  ),
  cv(
    'calendar',
    'timezone',
    'Timezone',
    'Calendar timezone.',
    'calendar.timezone',
    'implemented',
    'America/New_York',
  ),
  cv(
    'calendar',
    'booking_url',
    'Booking URL',
    'Public booking page URL.',
    'calendar.bookingUrl',
    'planned',
  ),

  // Lead (5)
  cv(
    'lead',
    'title',
    'Title',
    'Lead or opportunity title.',
    'lead.title',
    'implemented',
    'Botox inquiry',
  ),
  cv(
    'lead',
    'value',
    'Value',
    'Estimated deal value.',
    'lead.value',
    'implemented',
    '500',
  ),
  cv(
    'lead',
    'stage_name',
    'Stage name',
    'Current pipeline stage.',
    'lead.stageName',
    'implemented',
    'Qualified',
  ),
  cv(
    'lead',
    'pipeline_name',
    'Pipeline name',
    'Pipeline the lead belongs to.',
    'lead.pipelineName',
    'implemented',
    'Sales',
  ),
  cv(
    'lead',
    'source',
    'Source',
    'Lead source.',
    'lead.source',
    'implemented',
    'Form',
  ),

  // Form (4)
  cv(
    'form',
    'name',
    'Form name',
    'Submitted form name.',
    'form.name',
    'implemented',
    'Contact us',
  ),
  cv(
    'form',
    'submission_id',
    'Submission ID',
    'Unique submission identifier.',
    'form.submissionId',
    'implemented',
  ),
  cv(
    'form',
    'submitted_at',
    'Submitted at',
    'Submission timestamp.',
    'form.submittedAt',
    'implemented',
  ),
  cv(
    'form',
    'field_values',
    'Field values',
    'Dynamic form field values map.',
    'form.fieldValues',
    'stub',
  ),

  // Estimate (5)
  cv(
    'estimate',
    'number',
    'Number',
    'Estimate number.',
    'estimate.number',
    'implemented',
    'EST-1001',
  ),
  cv(
    'estimate',
    'total',
    'Total',
    'Estimate total amount.',
    'estimate.total',
    'implemented',
    '250.00',
  ),
  cv(
    'estimate',
    'status',
    'Status',
    'Estimate status.',
    'estimate.status',
    'implemented',
    'sent',
  ),
  cv(
    'estimate',
    'due_date',
    'Due date',
    'Estimate expiration or due date.',
    'estimate.dueDate',
    'implemented',
    'Jul 1, 2026',
  ),
  cv(
    'estimate',
    'public_url',
    'Public URL',
    'Customer-facing estimate link.',
    'estimate.publicUrl',
    'implemented',
  ),

  // Invoice (9)
  cv(
    'invoice',
    'number',
    'Number',
    'Invoice number.',
    'invoice.number',
    'implemented',
    'INV-2001',
  ),
  cv(
    'invoice',
    'total',
    'Total',
    'Invoice total amount.',
    'invoice.total',
    'implemented',
    '350.00',
  ),
  cv(
    'invoice',
    'subtotal',
    'Subtotal',
    'Invoice subtotal before tax.',
    'invoice.subtotal',
    'planned',
  ),
  cv(
    'invoice',
    'balance_due',
    'Balance due',
    'Remaining balance.',
    'invoice.balanceDue',
    'implemented',
    '150.00',
  ),
  cv(
    'invoice',
    'due_date',
    'Due date',
    'Payment due date.',
    'invoice.dueDate',
    'implemented',
    'Jul 15, 2026',
  ),
  cv(
    'invoice',
    'status',
    'Status',
    'Invoice status.',
    'invoice.status',
    'implemented',
    'sent',
  ),
  cv(
    'invoice',
    'public_url',
    'Public URL',
    'Customer-facing invoice link.',
    'invoice.publicUrl',
    'implemented',
  ),
  cv(
    'invoice',
    'payment_link',
    'Payment link',
    'Online payment checkout link.',
    'invoice.paymentLink',
    'implemented',
  ),
  cv(
    'invoice',
    'tax',
    'Tax',
    'Tax amount on the invoice.',
    'invoice.tax',
    'planned',
  ),

  // Payment (4)
  cv(
    'payment',
    'amount',
    'Amount',
    'Payment amount.',
    'payment.amount',
    'implemented',
    '200.00',
  ),
  cv(
    'payment',
    'date',
    'Date',
    'Payment date.',
    'payment.date',
    'implemented',
    'Jun 17, 2026',
  ),
  cv(
    'payment',
    'method',
    'Method',
    'Payment method.',
    'payment.method',
    'implemented',
    'card',
  ),
  cv(
    'payment',
    'reference',
    'Reference',
    'External payment reference.',
    'payment.reference',
    'implemented',
    'pi_abc123',
  ),

  // Conversation (2)
  cv(
    'conversation',
    'channel',
    'Channel',
    'Conversation channel.',
    'conversation.channel',
    'implemented',
    'whatsapp',
  ),
  cv(
    'conversation',
    'last_message_preview',
    'Last message',
    'Preview of the latest message.',
    'conversation.lastMessagePreview',
    'implemented',
    'Thanks!',
  ),

  // Service (4)
  cv(
    'service',
    'name',
    'Name',
    'Service name.',
    'service.name',
    'implemented',
    'Hydrafacial',
  ),
  cv(
    'service',
    'price',
    'Price',
    'Service price.',
    'service.price',
    'implemented',
    '150.00',
  ),
  cv(
    'service',
    'duration',
    'Duration',
    'Service duration in minutes.',
    'service.duration',
    'implemented',
    '45',
  ),
  cv(
    'service',
    'category',
    'Category',
    'Service category.',
    'service.category',
    'planned',
  ),

  // Task (3)
  cv(
    'task',
    'title',
    'Title',
    'Task title.',
    'task.title',
    'implemented',
    'Follow up call',
  ),
  cv(
    'task',
    'due_date',
    'Due date',
    'Task due date.',
    'task.dueDate',
    'implemented',
    'Jun 18, 2026',
  ),
  cv(
    'task',
    'status',
    'Status',
    'Task status.',
    'task.status',
    'implemented',
    'open',
  ),

  // Work item (2)
  cv(
    'work_item',
    'title',
    'Title',
    'Work item title.',
    'workItem.title',
    'implemented',
    'Install equipment',
  ),
  cv(
    'work_item',
    'status',
    'Status',
    'Work item status.',
    'workItem.status',
    'implemented',
    'in_progress',
  ),

  // Note (2)
  cv('note', 'body', 'Body', 'Note text content.', 'note.body', 'planned'),
  cv(
    'note',
    'created_at',
    'Created at',
    'When the note was created.',
    'note.createdAt',
    'planned',
  ),

  // Workflow (3)
  cv(
    'workflow',
    'run_id',
    'Run ID',
    'Current workflow run identifier.',
    'workflow.runId',
    'planned',
  ),
  cv(
    'workflow',
    'enrolled_at',
    'Enrolled at',
    'When the contact enrolled.',
    'workflow.enrolledAt',
    'planned',
  ),
  cv(
    'workflow',
    'current_step',
    'Current step',
    'Label of the active step.',
    'workflow.currentStep',
    'planned',
  ),
];

applyPlatformAudiencesToCustomValues(CUSTOM_VALUE_REGISTRY);

export const CUSTOM_VALUE_BY_KEY = Object.fromEntries(
  CUSTOM_VALUE_REGISTRY.map((v) => [v.key, v]),
) as Record<string, CustomValueDefinition>;
