/**
 * Design-token ownership: visual values live in globals.css / theme.
 * This file is a deprecated re-export of drawer recipes — not a second token system.
 *
 * @deprecated Import from `@/lib/design/drawer-tokens` instead.
 * Kept for backward-compatible import paths. New code must not add aliases here.
 */

export {
  DRAWER_SHELL_WIDTH_COMPACT,
  DRAWER_SHELL_WIDTH_STANDARD,
  DRAWER_SHELL_WIDTH_WIDE,
  DRAWER_SHELL_WIDTH_CONVERSATION,
  DRAWER_SHELL_WIDTH_SPLIT,
  DRAWER_SHELL_WIDTH_APPOINTMENT,
  DRAWER_SHELL_WIDTH_APPOINTMENT_MOBILE,
  drawerShellWidthClass,
  DRAWER_SHELL_HEADER_CLASS,
  DRAWER_SHELL_HEADER_ROW_CLASS,
  DRAWER_SHELL_HEADER_ACTIONS_CLASS,
  DRAWER_SHELL_HEADER_ACTION_CLASS,
  DRAWER_SHELL_TITLE_CLASS,
  DRAWER_SHELL_DESCRIPTION_CLASS,
  DRAWER_SHELL_BODY_CLASS,
  DRAWER_SHELL_CONTENT_INSET_CLASS,
  DRAWER_SHELL_FOOTER_CLASS,
  DRAWER_FIELD_CONTROL_CLASS,
  DRAWER_FIELD_LABEL_SHELL_CLASS as DRAWER_FIELD_LABEL_CLASS,
  DRAWER_FORM_FIELD_CLASS,
  DRAWER_FORM_ITEM_CLASS,
  DRAWER_FORM_DIVIDER_CLASS,
  DRAWER_FORM_STACK_CLASS,
  DRAWER_COMPACT_CONTENT_CLASS,
  DRAWER_COMPACT_FOOTER_CLASS,
  DRAWER_SCROLL_EDGE_CLASS,
  DRAWER_SCROLL_CONTENT_INSET_CLASS,
  DRAWER_SPINE_CLASS,
  DRAWER_SPINE_LABEL_CLASS,
  DRAWER_PRIMARY_FOOTER_BUTTON_CLASS,
  type DrawerShellWidthTier,
} from "@/lib/design/drawer-tokens";
