import type { LucideIcon } from "lucide-react";
import {
  AlignLeft,
  Calendar,
  CalendarClock,
  CheckSquare,
  CircleDot,
  Columns2,
  CreditCard,
  FileUp,
  Hash,
  Heading,
  Image,
  KeyRound,
  List,
  Mail,
  Minus,
  PenLine,
  Phone,
  Shield,
  SlidersHorizontal,
  Space,
  Star,
  TextCursorInput,
  ToggleLeft,
  Type,
  User,
  Globe,
  EyeOff,
} from "lucide-react";

export const FIELD_TYPE_ICONS: Record<string, LucideIcon> = {
  type: Type,
  mail: Mail,
  phone: Phone,
  hash: Hash,
  "key-round": KeyRound,
  "align-left": AlignLeft,
  list: List,
  "circle-dot": CircleDot,
  "check-square": CheckSquare,
  "toggle-left": ToggleLeft,
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  "file-up": FileUp,
  "pen-line": PenLine,
  star: Star,
  "sliders-horizontal": SlidersHorizontal,
  "eye-off": EyeOff,
  shield: Shield,
  "credit-card": CreditCard,
  user: User,
  globe: Globe,
  heading: Heading,
  "text-cursor-input": TextCursorInput,
  minus: Minus,
  space: Space,
  image: Image,
  "columns-2": Columns2,
};

const FIELD_TYPE_DEFAULT_ICONS: Record<string, LucideIcon> = {
  text: Type,
  email: Mail,
  phone: Phone,
  number: Hash,
  password: KeyRound,
  textarea: AlignLeft,
  select: List,
  multiselect: List,
  radio: CircleDot,
  checkbox: CheckSquare,
  toggle: ToggleLeft,
  date: Calendar,
  time: CalendarClock,
  datetime: CalendarClock,
  file: FileUp,
  signature: PenLine,
  rating: Star,
  range: SlidersHorizontal,
  hidden: EyeOff,
  captcha: Shield,
  collect_payment: CreditCard,
  name: User,
  address: Globe,
  website: Globe,
  heading: Heading,
  paragraph: TextCursorInput,
  divider: Minus,
  spacer: Space,
  image: Image,
  columns: Columns2,
};

export function getFieldTypeIcon(
  type: string,
  iconKey?: string | null,
): LucideIcon {
  if (iconKey && FIELD_TYPE_ICONS[iconKey]) {
    return FIELD_TYPE_ICONS[iconKey];
  }
  return FIELD_TYPE_DEFAULT_ICONS[type] ?? Type;
}
