export {
  STAFF_PERMISSION_GROUPS,
  STAFF_PERMISSION_KEYS,
  NOTIFICATION_SETTING_KEYS,
  DEFAULT_NOTIFICATION_SETTINGS,
  NAV_KEY_PERMISSION_MAP,
  SETTINGS_HREF_ACCESS,
  MEMBER_DEFAULT_SETTINGS_HREF,
  ADMIN_DEFAULT_SETTINGS_HREF,
  normalizeStaffPermissions,
  normalizeNotificationSettings,
  hasStaffPermission,
  canAccessSettingsHref,
  resolveSettingsHrefAccessRule,
  type StaffPermissionKey,
  type StaffNotificationSettingKey,
  type SettingsHrefAccessRule,
} from "./staff-permission-registry";
